login/urls.py
from django.urls import path, include
from django.contrib.auth.models import User
from login import views


app_name = 'login'
urlpatterns = [
    path('', views.home, name='home'),
    path('login_cliente/', views.login_cliente, name='login_cliente'),
    path('cadastro_cliente/', views.cadastro_cliente, name='cadastro_cliente'),
    path('cadastro_vendedor/', views.cadastro_vendedor, name='cadastro_vendedor'),
    path('login_vendedor/', views.login_vendedor, name='login_vendedor')
]

menu/urls.py
from django.urls import path
from django.contrib.auth.models import User
from menu import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu, name='menu'),
    path('dashboard_cliente/', views.dashboard_cliente, name='dashboard_cliente'),
    path('registrar_produto/', views.registrar_produto, name='registrar_produto'),
    path('comprar_produto/', views.comprar_produto, name='comprar_produto')
]

truffles/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('menu/', include('menu.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User

class Cliente(models.Model):
    nome = models.CharField(max_length=50)
    telefone = models.CharField(max_length=15, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    
    def __str__(self):
        return self.nome
    
class Vendedor(models.Model):
    nome = models.CharField(max_length=50)
    telefone = models.CharField(max_length=15, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

def __str__(self):
        return self.nome



    



    

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.db import models
from .models import Cliente, Vendedor
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse

def home(request):
    return render(request, 'home.html')

def login_cliente(request): 
    if request.POST:
        username = request.POST.get('login')
        senha = request.POST.get('senha')
        user = authenticate(username=username, password=senha)
        print(user, username, senha)
        if user is not None:
            login(request, user)
            return redirect(reverse('menu:dashboard_cliente'))
        else:
            messages.error(request, 'Erro no login ou senha')
    return render(request, 'login_cliente.html')

def cadastro_cliente(request):
    if request.POST:
        username = request.POST.get('login')
        senha = request.POST.get('senha')
        nome = request.POST.get('nome')
        telefone = request.POST.get('telefone')
        cliente = Cliente.objects.filter(user__username=username).first()  # Verifica se o usuário já existe

        # Cria o usuário e registra comum
        if cliente is None:
            cliente = Cliente(nome=nome, telefone=telefone) 
            user = User.objects.create_user(username=username, password=senha)
            user.save()
            user
            cliente.user = user
            cliente.save()
             # Use o modelo CustomUser
            return redirect("login:login_cliente")
        else:
            messages.error(request, "Usuário já cadastrado")
            return render(request, 'cadastro_cliente.html')

    return render(request, 'cadastro_cliente.html')

def cadastro_vendedor(request):
    if request.POST:
        username = request.POST.get('login')
        senha = request.POST.get('senha')
        nome = request.POST.get('nome')
        telefone = request.POST.get('telefone')
        vendedor = Vendedor.objects.filter(user__username=username).first()  # Verifica se o usuário já existe

        if vendedor is None:
            vendedor = Vendedor(nome=nome, telefone=telefone) 
            user = User.objects.create_superuser(username=username, password=senha)
            user.is_active = False
            user.is_staff = True
            user.save()
            user
            vendedor.user = user
            vendedor.save()
             # Use o modelo CustomUser
            return redirect("login:login_vendedor")
        else:
            messages.error(request, "Vendedor já cadastrado")
            messages.error(request, 'Telefone já cadastrado')
            return render(request, 'cadastro_vendedor.html')

    return render(request, 'cadastro_vendedor.html')

def login_vendedor(request):
    if request.POST:
        username = request.POST.get('login')
        senha = request.POST.get('senha')
        user = authenticate(username=username, password=senha)
        print(user, username, senha)
        if user is not None:
            login(request, user)
            return redirect('/menu')
        else:
            messages.error(request, 'Erro no login ou senha')
    return render(request, 'login_vendedor.html')

def sair(request):
    logout(request)
    return redirect('login:home')

login/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Truffles</title>  
    {% endblock  %}

    <!-- Styles/boostrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/log_cad_cliente.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/bootstrap-icons.min.css' %}">
</head>
<body>

    <!-- Navbar -->
    {% block navbar %}
    <nav class="container-fluid navbar navbar-expand-lg nav-underline sticky-top bg-light pb-4 pt-4">
        <div class="container-fluid">
            <a class="navbar-brand ps-lg-4 ms-5" href="http://127.0.0.1:8000">Truffles</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-lg-center" id="navbarTogglerDemo02">

            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item me-3 ms-3">
                    <a class="nav-link active" id="nav-link-home" href="http://127.0.0.1:8000">Home</a>
                </li>
                <li class="nav-item me-3 ms-3">
                    <a class="nav-link" id="nav-link-menu" href="/login_cliente">Menu</a>
                </li>
                <li class="nav-item me-3 ms-3">
                    <a class="nav-link" id="nav-link-contato" href="#contato">Contato</a>
                </li>
            </ul>
            </div>

            <div class="d-lg-flex justify-content-lg-end me-5 pe-4" id="person_icon_box">
                <i class="bi bi-person"></i>
            </div>
        </div>
    </nav>
    {% endblock  %}
  
    {%block conteudo%}{%endblock%}

    <!-- Scripts -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    
    {%block scripts%}{%endblock%}
</body>
</html>

login/templates/cadastro_cliente.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Cadastro</title>
{% endblock  %}

{% block navbar %}
    
{% endblock  %}

{% block conteudo %}
<div class="fundo d-flex justify-content-center align-items-center">
    <main class="w-75 m-auto formulario">
        <form method="post" enctype="multipart/form-data" action="{% url 'login:cadastro_cliente' %}" onsubmit="return validarForm()">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div>
                <h2 class="py-3">Cadastre-se</h2>
            </div>
            <div class="form-floating mb-4">
                <input type="text" placeholder="Nome" name="nome" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Nome</label>
            </div>
            <div class="form-floating mb-4">
                <input type="text" placeholder="Telefone" name="telefone" class="form-control opacity-50" id="telefoneInput">
                <label class="nome_input" for="telefoneInput">Telefone</label>
            </div>
            <div class="form-floating mb-4">
                <input type="password" placeholder="Senha" name="senha" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Senha</label>
            </div>
            <div class="form-floating mb-4">
                <input type="text" placeholder="Login" name="login" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Login</label>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <a class="button btn btn-dark py-2 px-3" href="/login_cliente">Cancelar</a>
                <button class="btn py-2 btn-danger">Cadastrar</button>
            </div>
        </form>
    </main>
</div>

<script>
function validarForm() {
    var telefoneInput = document.getElementById('telefoneInput');
    var telefoneValue = telefoneInput.value;

    var telefoneRegex = /^\d+$/;

    if (!telefoneRegex.test(telefoneValue)) {
        alert("O campo Telefone deve conter apenas números.");
        telefoneInput.focus();
        return false;
    }

    return true;
}
</script>
{% endblock %}

login/templates/cadastro_vendedor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Cadastro de vendedor</title>
{% endblock  %}

{% block navbar %}
    
{% endblock  %}

{% block conteudo %}
<div class="fundo d-flex justify-content-center align-items-center">
    <main class="w-75 m-auto formulario">
        <form method="post" enctype="multipart/form-data" action="{% url 'login:cadastro_vendedor' %}" onsubmit="return validarForm()">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div>
                <h2 class="py-3">Cadastre-se como vendedor</h2>
            </div>
            <div class="form-floating mb-4">
                <input type="text" placeholder="Nome" name="nome" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Nome</label>
            </div>
            <div class="form-floating mb-4">
                <input type="text" placeholder="Telefone" name="telefone" class="form-control opacity-50" id="telefoneInput">
                <label class="nome_input" for="telefoneInput">Telefone</label>
            </div>
            <div class="form-floating mb-4">
                <input type="password" placeholder="Senha" name="senha" class="form-control opacity-50" id="senhaInput">
                <label class="nome_input" for="senhaInput">Senha</label>
            </div>
            <div class="form-floating mb-4">
                <input type="text" placeholder="Login" name="login" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Login</label>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <a class="button btn btn-dark py-2 px-3" href="/login_vendedor">Cancelar</a>
                <button class="btn py-2 btn-danger">Cadastrar</button>
            </div>
        </form>
    </main>
</div>

<script>
function validarForm() {
    var telefoneInput = document.getElementById('telefoneInput');
    var telefoneValue = telefoneInput.value;

    var telefoneRegex = /^\d+$/;

    if (!telefoneRegex.test(telefoneValue)) {
        alert("O campo Telefone deve conter apenas números.");
        telefoneInput.focus();
        return false;
    }

    var senhaInput = document.getElementById('senhaInput');
    var senhaValue = senhaInput.value;

    var senhaRegex = /^(?=.*[!@#$%^&*(),.?":{}|<>])(?=.*[0-9a-zA-Z]).{6,12}$/;

    if (!senhaRegex.test(senhaValue)) {
        alert("A senha deve conter pelo menos um caractere especial e ter entre 6 e 12 dígitos.");
        senhaInput.focus();
        return false;
    }

    return true;
}
</script>
{% endblock %}

login/templates/home.html
{%extends 'base.html'%} 
{%load static %} 

{% block title %}
<title>Home</title>
{% endblock  %}


{%block conteudo%}

<main>
    <section class="container-fluid mb-3" style="background-image: url(static/img/background_hero.png);">
        <div class="container py-5 justify-content-lg-center">
            <div class="row align-items-center">
                <div class="col-6" id="hero_text">
                    <h1 class="display-2 mb-3 title-hero">Os melhores doces do campus</h1>
                    <p class="fs-3">delicias a um click</p>
                    
                    <a class="btn btn_background_secondary text-white btn-lg rounded-pill px-5" href="/login_cliente">Menu</a>
                </div>
                <div class="col-6" id="hero_img">
                    <img class="image-fluid" src="{% static 'img/doces_hero.png' %}" alt="">
                </div>
            </div>
        </div>
    </section>

    <section class="container-fluid mb-4">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <h2 class="text_basic mb-3 mt-5 col-12 text-center">Nossas variadades</h2>
                <h1 class="bold col-12 text-center mb-2">Doces</h1>
                <h4 class="text-center">Os melhores doces de SPP!</h4>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="card mx-auto mb-5" style="width: 18rem;">
                        <img src="{% static 'img/bonbon1.png' %}" class="card-img-top p-4" alt="...">
                        <div class="card-body card-body-product pb-2">
                            <h4 class="card-title bold text-center">Alfajor</h4>
                            <p class="card-text text-center">Lorem ipsum</p>
                            <div class="row align-items-center">
                                <div class="col-10">
                                    <h3>R$ 3.00</h3>
                                </div>
                                <div class="col-2">
                                    <i class="bi bi-heart-fill" style="font-size: 1.2rem;"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card mx-auto mb-5" style="width: 18rem;">
                        <img src="{% static 'img/bonbon2.png' %}" class="card-img-top p-4" alt="...">
                        <div class="card-body card-body-product pb-2">
                            <h4 class="card-title bold text-center">Trufa</h4>
                            <p class="card-text text-center">Lorem ipsum</p>
                            <div class="row align-items-center">
                                <div class="col-10">
                                    <h3>RS 3.00</h3>
                                </div>
                                <div class="col-2">
                                    <i class="bi bi-heart-fill" style="font-size: 1.2rem;"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card mx-auto mb-5" style="width: 18rem;">
                        <img src="{% static 'img/bonbon3.png' %}" class="card-img-top p-4" alt="...">
                        <div class="card-body card-body-product pb-2">
                            <h4 class="card-title bold text-center">Cone trufado</h4>
                            <p class="card-text text-center">Lorem ipsum </p>
                            <div class="row align-items-center">
                                <div class="col-10">
                                    <h3>RS 3.00</h3>
                                </div>
                                <div class="col-2">
                                    <i class="bi bi-heart-fill" style="font-size: 1.2rem;"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="contato">
        <div class="container-fluid" style="background-image: url(static/img/background_footer.png); background-repeat: no-repeat; background-size: cover;">
            <div class="container py-4">
                <h1 class="bold text-center mb-3"> Entre em contato</h1>
                <h4 class="text-center">IFRN - Campus SPP</h4>
                <h4 class="text-center">+55 (84) 98708-7658</h4>
                <h4 class="text-center mb-3">LayzaDasTrufa@gmail.com</h4>

                <div class="row justify-content-center pb-4" style="border-bottom: 1px solid #4C8670;">
                    <div class="col-12 text-center">
                        <div class="btn-group" role="group">
                            <button type="button" class="btn btn-light btn-rede p-3 px-4 me-2 ms-2 rounded-5"><i class="bi bi-instagram" style="font-size: 1.4rem;"></i></button>
                            <button type="button" class="btn btn-light btn-rede p-3 px-4 me-2 ms-2 rounded-5"><i class="bi bi-whatsapp" style="font-size: 1.4rem;"></i></button>
                            <button type="button" class="btn btn-light btn-rede p-3 px-4 me-2 ms-2 rounded-5"><i class="bi bi-twitter" style="font-size: 1.4rem;"></i></button>
                        </div>
                    </div>
                </div>
                <h4 class="text-center pb-2 pt-5">© 2023 Truffles. ALL RIGHT RESERVED.</h4>
            </div>
        </div>
    </section>
</main>

{%endblock%} 
{%block scripts%}
<script>
  $(document).ready(function () {
    

    if ($(window).width() < 992) {
        $("#person_icon_box").hide();
        $("#hero_text").removeClass("col-6");
        $("#hero_img").removeClass("col-6");
        $("#hero_text").addClass("col-12");
        $(".nav-item").removeClass("me-3");
        $(".nav-item").removeClass("ms-3");
        $("#hero_img").hide();
    }

    $(window).resize(function () {
        if ($(window).width() < 992) {
            $("#person_icon_box").hide();
            $("#hero_text").removeClass("col-6");
            $("#hero_img").removeClass("col-6");
            $("#hero_img").hide()
            $("#hero_text").addClass("col-12");

            $(".nav-item").removeClass("me-3");
            $(".nav-item").removeClass("ms-3");
        } else {
            $("#person_icon_box").show();
            $("#hero_img").show();
            $("#hero_text").removeClass("col-12");
            $("#hero_text").addClass("col-6");
            $("#hero_img").addClass("col-6");

            $(".nav-item").addClass("me-3");
            $(".nav-item").addClass("ms-3");
        }
    });
  });
</script>
{%endblock%}

login/templates/login_cliente.html
{%extends 'base.html'%}
{%load static %}

{% block title %}
<title>Login</title>
{% endblock  %}

{% block navbar %}
    
{% endblock  %}

{%block conteudo%}
<div class="fundo d-flex justify-content-center align-items-center">
    <main class="w-100 m-auto formulario">
        <form class="p-3" method="post">
            {% csrf_token %}
            <div>
                <h2>Login</h2>
            </div>
            {% if messages %}
        
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="form-floating mb-3">
                <input type="text" placeholder="Login" name="login" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Login</label>
            </div>
            <div class="form-floating mb-4">
                <input type="password" placeholder="Senha" name="senha" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Senha</label>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <a class="text-dark" href="/cadastro_cliente">Não tenho conta criada</a>
                <input type="submit" class="btn py-2 btn-danger py-2 px-3 custom_btn" value="Entrar" style="color: rgb(255, 255, 255); 
                font-size: 16px; 
                background-color: #DC414C; "/>
            </div>
        </form>
    </main>
</div>
{%endblock%}

login/templates/login_vendedor.html
{%extends 'base.html'%}
{%load static %}

{% block title %}
<title>Login vendedor</title>
{% endblock  %}

{% block navbar %}
    
{% endblock  %}

{%block conteudo%}
<div class="fundo d-flex justify-content-center align-items-center">
    <main class="w-100 m-auto formulario">
        <form class="p-3" method="post">
            {% csrf_token %}
            <div>
                <h2>Vendedor, faça seu login</h2>
            </div>
            {% if messages %}
        
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="form-floating mb-3">
                <input type="text" placeholder="Login" name="login" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Login</label>
            </div>
            <div class="form-floating mb-4">
                <input type="password" placeholder="Senha" name="senha" class="form-control opacity-50" id="floatingInput">
                <label class="nome_input" for="floatingInput">Senha</label>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <a class="text-dark" href="/cadastro_vendedor">Não tenho conta criada</a>
                <input type="submit" class="btn py-2 btn-danger py-2 px-3 custom_btn" value="Entrar" style="color: rgb(255, 255, 255); 
                font-size: 16px; 
                background-color: #DC414C; "/>
            </div>
        </form>
    </main>
</div>
{%endblock%}