menu/urls.py
from django.urls import path
from django.contrib.auth.models import User
from menu import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu, name='menu'),
    path('dashboard_cliente/', views.dashboard_cliente, name='dashboard_cliente'),
    path('registrar_produto/', views.registrar_produto, name='registrar_produto'),
    path('comprar_produto/', views.comprar_produto, name='comprar_produto')
]

truffles/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('menu/', include('menu.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models
from django.contrib.auth.models import User

class Sabor(models.TextChoices):
    CHOCOLATE = 'chocolate', 'Chocolate'
    DOCE_DE_LEITE = 'doce_de_leite', 'Doce de leite'
    MORANGO = 'morango', 'Morango'

class Produto(models.Model):
    nome = models.CharField(max_length=50)
    sabor = models.CharField(max_length=20, choices=Sabor.choices)
    preco = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    quantidade = models.IntegerField()
    imagem = models.ImageField(upload_to='media/')

    def get_produto(self):
        return Produto.objects.filter(produto_id=self.id)

    def __str__(self):
        return self.nome

    

menu/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from .models import Produto
from login.models import Cliente, Vendedor
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

def menu(request):
    produtos = Produto.objects.all()
    return render(request, 'dashboard_vendedor.html', {'produtos': produtos})


@login_required(login_url="login:/login_cliente/")
def dashboard_cliente(request):
    produtos = Produto.objects.all()
    context = {}
    context['produtos'] = produtos
    context['cliente'] = Cliente.objects.filter(user_id=request.user.id).first()
    return render(request, 'dashboard_cliente.html', context)

def registrar_produto(request):
    if request.method == 'POST':
        nome_produto = request.POST.get('nome_produto')
        preco_produto = request.POST.get('preco_produto')
        imagem_produto = request.FILES.get('imagem_produto')
        quantidade_produto = request.POST.get('quantidade_produto')
        sabor_produto = request.POST.get('sabor_produto')

        # Verificações
        if not nome_produto or not preco_produto or not imagem_produto or not quantidade_produto or not sabor_produto:
            messages.error(request, 'Preencha todos os campos.')
        elif not nome_produto.isalpha() or not sabor_produto.isalpha():
            messages.error(request, 'Os campos "Nome" e "Sabor" devem conter apenas letras.')
        elif float(preco_produto) < 0 or int(quantidade_produto) < 0:
            messages.error(request, 'Os campos "Preço" e "Quantidade" não podem ser negativos.')
        else:
            # Tudo está correto, podemos criar o produto
            Produto.objects.create(
                nome=nome_produto,
                preco=preco_produto,
                imagem=imagem_produto,
                quantidade=quantidade_produto,
                sabor=sabor_produto
            )
            messages.success(request, 'Produto cadastrado com sucesso!')
            return redirect('menu:menu')

    return render(request, 'registrar_produto.html')

def comprar_produto(request, pk):
    produto = Produto.objects.filter(id=pk).first()
    if request.method == 'POST':
        quantidade_produto = request.POST.get('quantidade_produto')
        sabor_produto = request.POST.get('sabor_produto')
        
        # Verificações de validade da quantidade
        if quantidade_produto <= 0:
            return render(request, {'mensagem': 'A quantidade deve ser maior que zero.'})

        if quantidade_produto > produto.quantidade:
            return render(request, {'mensagem': 'A quantidade desejada excede o estoque disponível.'})
        
        try:
            quantidade_produto = int(quantidade_produto)
        except ValueError:
            return render(request, 'dashboard_cliente.html', {'mensagem': 'A quantidade deve ser um número inteiro válido.'})

        
        produto.quantidade -= quantidade_produto
        produto.save()


        return HttpResponseRedirect('/dashboard_cliente/')

    return render(request, 'dashboard_cliente.html', {'produto': produto}, {'sabor': sabor_produto})
    
def sair(request):
    logout(request)
    return redirect('login:home')

menu/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Truffles</title>  
    {% endblock  %}

    <!-- Styles/boostrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/log_cad_cliente.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/bootstrap-icons.min.css' %}">
</head>
<body>

    <!-- Navbar -->
    {% block navbar %}
        
    {% endblock  %}
  
    {%block conteudo%}{%endblock%}

    <!-- Scripts -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    
    {%block scripts%}{%endblock%}
</body>
</html>

menu/templates/dashboard_cliente.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Dashboard</title>
{% endblock  %}

{% block conteudo %}

<main>
    <div class="container">
        <div class="page-title mt-5 row">
            <div class="col-8">
                <h1>Olá, {{ cliente.nome }}</h1>
            </div>
        </div>
        
        <section class="catalogo mt-5">
            <h2>Produtos disponíveis</h2>
            <div class="produtos row mt-3">
                {% for produto in produtos %}
                <div class="col-4">
                    <div class="card">
                        <img src="/media/{{ produto.imagem }}" class="card-img-top" alt="Imagem do Produto">
                        <div class="card-body">
                            <h5 class="card-title">{{ produto.nome }}</h5>
                            <p class="card-text">Sabores: {{ produto.sabor }}</p>
                            <p class="card-text">Preço: {{ produto.preco }}</p>
                            <button type="button" class="btn btn-primary btn-comprar" data-bs-toggle="modal" data-bs-target="#comprar_produto_modal" data-produto-id="{{ produto.id }}">Comprar</button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>

        <!-- Modal de Compra -->
        <div class="modal fade" id="comprar_produto_modal" tabindex="-1" aria-labelledby="comprar_produto" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title fs-5" id="modal-lable">
                            Comprar Produto
                        </div>
                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="quantidade_produto" class="form-label">Quantidade</label>
                                <input type="number" class="form-control" id="quantidade_produto" name="quantidade_produto" min="1" required>
                            </div>
                            <div class="form-floating mb-3">
                                <select name="sabor_produto" class="form-control opacity-50" id="floatingInputSabor">
                                    <option value="" disabled selected>Selecione o sabor</option>
                                    <option value="chocolate">Chocolate</option>
                                    <option value="doce_de_leite">Doce de leite</option>
                                    <option value="morango">Morango</option>
                                </select>
                                <label class="nome_input" for="floatingInputSabor">Sabor</label>
                            </div>
                            <div class="mb-3">
                                <label for="valor_total" class="form-label">Valor Total: R$ <span id="valor_total">0.00</span></label>
                            </div>
                            <button type="submit" class="btn btn-success">Comprar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Seu código existente aqui -->
    </div>
</main>

{% endblock  %}

{% block scripts %}
<script>
    $(document).ready(function() {
        $('#nav-link-home').removeClass('active');
        $('#nav-link-menu').addClass('active');

        // Atualiza o valor total com base na quantidade escolhida
        $('#quantidade_produto').on('input', function() {
            var quantidade = $(this).val();
            var precoUnitario = parseFloat(' {{produto.preco}} '); 
            var valorTotal = quantidade * precoUnitario;
            $('#valor_total').text(valorTotal.toFixed(2));
        });

        // Abre o modal quando o botão de comprar é clicado
        $('.btn-comprar').on('click', function() {
            $('#comprar_produto_modal').modal('show');
        });
    });
</script>
{% endblock %}

menu/templates/dashboard_vendedor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Dashboard</title>
{% endblock  %}

{% block conteudo %}



<main>
    <div class="container">
        <div class="page-title mt-5 row">
            <div class="col-8">
                <h1>Olá, {{vendedor.nome}}</h1>
            </div>
            <div class="col-4 d-flex gap-2">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#registrar_produto_modal">Adicionar produto</button>
                <button type="button" class="btn btn-success">Liberar produtos</button>
            </div>
        </div>
        
        <section class="catalogo mt-5">
            <h2>Produtos registrados</h2>
            <div class="produtos row mt-3">
                {% for produto in produtos %}
                <div class="col-4">
                    <div class="card">
                        <img src="/media/{{ produto.imagem }}" class="card-img-top" alt="Imagem do Produto">
                        <div class="card-body">
                            <h5 class="card-title">{{ produto.nome }}</h5>
                            <p class="card-text">Sabores: {{ produto.sabor }}</p>
                            <p class="card-text">Preço: {{ produto.preco }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>

        <!-- Modal -->
        <div class="modal fade" id="registrar_produto_modal" tabindex="-1" aria-labelledby="registrar_produto" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title fs-5" id="modal-lable">
                            Novo produto
                        </div>
                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="mb-3">
                                <label for="nome_produto" class="form-label">Produto</label>
                                <input type="text" class="form-control" id="nome_produto">
                            </div>
                            <div class="mb-3">
                                <label for="sabor_produto" class="form-label">Sabor</label>
                                <input type="text" class="form-control" id="sabor_produto">
                            </div>
                            <div class="mb-3">
                                <label for="preco_produto" class="form-label">Preço</label>
                                <input type="text" class="form-control" id="preco_produto">
                            </div>
                            <div class="mb-3">
                                <label for="quantidade_produto" class="form-label">Quantidade</label>
                                <input type="number" class="form-control" id="quantidade_produto">
                            </div>
                            <div class="mb-3">
                                <label for="imagem_produto" class="form-label">Imagem</label>
                                <input type="text" class="form-control" id="imagem_produto">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-success">Adicionar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


{% endblock  %}

{% block scripts %}

<script>
    $(document).ready(function() {
        $('#nav-link-home').removeClass('active');
        $('#nav-link-menu').addClass('active');
    });
</script>
    
{% endblock %}

menu/templates/registrar_produto.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Registrar produto</title>
{% endblock  %}

{% block navbar %}
    <!-- Se precisar adicionar algo à navbar -->
{% endblock  %}

{% block conteudo %}
<div class="fundo d-flex justify-content-center align-items-center">
    <main class="w-75 m-auto formulario">
        <form method="post" enctype="multipart/form-data" action="{% url 'menu:registrar_produto' %}">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div>
                <h2 class="py-3">Produto</h2>
            </div>
            <div class="form-floating mb-4">
                <input type="text" placeholder="Nome" name="nome_produto" class="form-control opacity-50" id="floatingInputNome">
                <label class="nome_input" for="floatingInputNome">Nome</label>
            </div>
            <div class="form-floating mb-4">
                <input type="number" placeholder="Preço" name="preco_produto" class="form-control opacity-50" id="floatingInputPreco">
                <label class="nome_input" for="floatingInputPreco">Preço</label>
            </div>
            <div class="form-floating mb-3">
                <input type="file" name="imagem_produto" class="form-control opacity-50" id="fotoInput" accept="image/*">
                <label for="fotoInput">Foto</label>
            </div>
            <div class="form-floating mb-4">
                <input type="number" placeholder="Quantidade" name="quantidade_produto" class="form-control opacity-50" id="floatingInputQuantidade">
                <label class="nome_input" for="floatingInputQuantidade">Quantidade</label>
            </div>
            <div class="form-floating mb-4">
                <select name="sabor_produto" class="form-control opacity-50" id="floatingInputSabor">
                    <option value="" disabled selected>Selecione o sabor</option>
                    <option value="chocolate">Chocolate</option>
                    <option value="doce_de_leite">Doce de leite</option>
                    <option value="morango">Morango</option>
                </select>
                <label class="nome_input" for="floatingInputSabor">Sabor</label>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <a class="button btn btn-dark py-2 px-3" href="{% url 'menu:menu' %}">Cancelar</a>
                <button class="btn py-2 btn-danger" type="submit">Registrar</button>
            </div>
        </form>
    </main>
</div>

{% endblock %}